--[[ 
AUDAC NIO240 Q-SYS Plugin
Author: Nikita Visual Arts / Generated by GPT-5.1-Codex-Max
Version: 1.0.0
ID: c3d5a4c1-8c3f-4a2f-9f1b-7c8c83931d9c

Description:
Production-ready Q-SYS plugin for controlling the AUDAC NIO family (focused on NIO240) using the ASCII protocol.
Supports per-input/per-output mute and volume, stereo pairing, connection settings, and automation pins.

Setup Notes:
- Place logo assets as plugin resources named "audac_logo.png" and "nikita_logo.png" to display in the header.
- Use the Settings page to set the Device IP, Port (per manual), Device Address, and optional LocalPort (UDP source port; 0 = auto).
- Transport defaults to UDP for the AUDAC ASCII protocol. The abstraction can be adapted to TCP if needed.
- Designed/tested against AUDAC NIO240 firmware v1.1.0 (per command manual).
- Reference: AUDAC NIO240 Command Manual (https://audac.eu/eu/products/d/nio240---network-i-o-mixing-breakout-box-dante-aes67---4-x-mic-line-inputs/command-manual)

Mapping Table (UI / Pins -> AUDAC Commands):
- Inputs Line n: Mute -> TARGET "INPUT_LINE>n>VOLUME>1", COMMAND "MUTE"
- Inputs Line n: Volume -> TARGET "INPUT_LINE>n>VOLUME>1", COMMAND "VOLUME"
- Inputs Dante n: Mute/Volume -> TARGET "INPUT_DANTE>n>VOLUME>1"
- Inputs Bluetooth n: Mute/Volume -> TARGET "INPUT_BLUETOOTH>n>VOLUME>1"
- Outputs Dante n: Mute/Volume -> TARGET "OUTPUT_DANTE>n>VOLUME>1"
- Stereo pairs map to paired channels and push linked commands to both member channels.
- Global All Inputs/Outputs Mute -> TARGET "ALL_IN" or "ALL_OUT", COMMAND "MUTE" (uses grouped command).

Test Plan (manual validation):
1) Connectivity: Set IP/Port/Address, observe Online indicator -> send GET_REQ for an input, confirm response updates control.
2) Per-channel mute/volume: Toggle mute and move fader for Line 1; verify device state and plugin feedback sync.
3) Stereo pairing: Pair Line 1+2, adjust pair fader/mute; confirm both channels track and device states match.
4) Reconnect/failure: Disconnect network, ensure plugin shows Offline and retries; reconnect and confirm state repolls.
]]

local PluginInfo = {
  Name = "AUDAC NIO240 Control",
  Version = "1.0.0",
  Id = "c3d5a4c1-8c3f-4a2f-9f1b-7c8c83931d9c",
  Description = "Control plugin for AUDAC NIO family (NIO240 focus) via ASCII protocol",
  ShowDebug = false,
  Author = "Nikita Visual Arts"
}

-- Utility: bit32 is available in Q-SYS Lua runtime
local function crc16(data)
  local crc = 0xFFFF
  for i = 1, #data do
    crc = bit32.bxor(crc, string.byte(data, i))
    for _ = 1, 8 do
      local lsb = bit32.band(crc, 1)
      crc = bit32.rshift(crc, 1)
      if lsb ~= 0 then
        crc = bit32.bxor(crc, 0xA001)
      end
    end
  end
  return string.format("%04X", bit32.band(crc, 0xFFFF))
end

local function trim(s)
  return (s and s:gsub("^%s+", ""):gsub("%s+$", "")) or ""
end

-- Transport abstraction (UDP-focused; easily adapted for TCP if needed)
local Transport = {}
Transport.__index = Transport

function Transport:new(onData, onStatus)
  local t = {
    socket = nil,
    onData = onData,
    onStatus = onStatus,
    connected = false,
    buffer = ""
  }
  setmetatable(t, Transport)
  return t
end

function Transport:connect(host, port, localPort)
  if self.socket then
    self.socket:Close()
    self.socket = nil
  end
  self.socket = UdpSocket.New()
  self.socket.ReadTimeout = 1
  self.socket.WriteTimeout = 1
  self.socket.EventHandler = function(sock, evt)
    if evt == UdpSocket.Events.Closed then
      self.connected = false
      if self.onStatus then self.onStatus("Closed") end
    elseif evt == UdpSocket.Events.Error then
      self.connected = false
      if self.onStatus then self.onStatus("Error: " .. (sock.LastError or "Unknown")) end
    elseif evt == UdpSocket.Events.Data then
      local data = sock:Read(sock:BytesAvailable()) or ""
      if #data > 0 then
        self.buffer = self.buffer .. data
        if self.onData then
          local remainder = self.onData(self.buffer)
          if type(remainder) == "string" then
            self.buffer = remainder
          else
            self.buffer = ""
          end
        end
      end
    end
  end
  local ok, err = pcall(function() self.socket:Open(localPort or 0) end)
  self.host = host
  self.port = port
  self.connected = ok
  if not ok and self.onStatus then
    self.onStatus("Error: " .. tostring(err))
  elseif ok and self.onStatus then
    self.onStatus("Connected")
  end
end

function Transport:send(payload)
  if self.socket and self.connected then
    self.socket:Write(payload, self.host, self.port)
  end
end

function Transport:close()
  if self.socket then
    self.socket:Close()
    self.connected = false
  end
end

-- Command builder/parser
local function build_command(destAddr, target, command, args, requestType)
  local destination = string.format("NIO240>%s", destAddr or "1")
  local source = "QSYS"
  local msgType = requestType or "SET_REQ"
  local arguments = args or ""
  local frame = string.format("#|%s|%s|%s^%s^%s|%s|", destination, source, msgType, target, command, arguments)
  local crc = crc16(frame)
  return frame .. crc .. "|\r\n"
end

local function parse_response(raw)
  local responses = {}
  local remainder = ""
  local idx = 1
  while true do
    local s, e = raw:find("\r?\n", idx)
    if not s then
      remainder = raw:sub(idx)
      break
    end
    local line = raw:sub(idx, s - 1)
    idx = e + 1
    if line:sub(1, 1) == "#" then
      local parts = {}
      for part in line:gmatch("([^|]+)|") do
        table.insert(parts, part)
      end
      if #parts >= 5 then
        local destination = parts[1]:gsub("^#", "")
        local source = parts[2]
        local typeBlock = parts[3]
        local targetCommand = parts[4]
        local args = parts[5]
        local tTarget, tCommand = targetCommand:match("([^%^]+)%^(.*)")
        local msgType, target, command = typeBlock:match("([^%^]+)%^([^%^]+)%^(.*)")
        table.insert(responses, {
          destination = destination,
          source = source,
          msgType = msgType or typeBlock,
          target = target or tTarget,
          command = command or tCommand,
          args = args
        })
      end
    end
  end
  return responses, remainder
end

-- Channel/state definitions
local channelDefinitions = {
  inputs_line = { baseTarget = "INPUT_LINE", count = 4, label = "Line", type = "input" },
  inputs_dante = { baseTarget = "INPUT_DANTE", count = 4, label = "Dante In", type = "input" },
  inputs_bt = { baseTarget = "INPUT_BLUETOOTH", count = 2, label = "Bluetooth", type = "input" },
  outputs_dante = { baseTarget = "OUTPUT_DANTE", count = 4, label = "Dante Out", type = "output" }
}

local function buildChannelId(base, index, suffix)
  return string.format("%s_%d_%s", base, index, suffix)
end

local channelState = {}
local stereoPairs = {
  { key = "line_1_2", members = { "inputs_line_1", "inputs_line_2" }, label = "Line 1+2" },
  { key = "line_3_4", members = { "inputs_line_3", "inputs_line_4" }, label = "Line 3+4" },
  { key = "dante_in_1_2", members = { "inputs_dante_1", "inputs_dante_2" }, label = "Dante In 1+2" },
  { key = "dante_in_3_4", members = { "inputs_dante_3", "inputs_dante_4" }, label = "Dante In 3+4" },
  { key = "bt_1_2", members = { "inputs_bt_1", "inputs_bt_2" }, label = "Bluetooth 1+2" },
  { key = "dante_out_1_2", members = { "outputs_dante_1", "outputs_dante_2" }, label = "Dante Out 1+2" },
  { key = "dante_out_3_4", members = { "outputs_dante_3", "outputs_dante_4" }, label = "Dante Out 3+4" }
}

local pairModes = { "Off", "Linked" }
local pairModeState = {}
local pollTimer = Timer.New()
local queueTimer = Timer.New()
local reconnectTimer = Timer.New()

-- Properties
function GetProperties()
  return {
    { Name = "DeviceIP", Type = "string", Value = "192.168.1.100" },
    { Name = "DevicePort", Type = "integer", Min = 1, Max = 65535, Value = 8010 },
    { Name = "DeviceAddress", Type = "integer", Min = 1, Max = 99, Value = 1 },
    { Name = "LocalPort", Type = "integer", Min = 0, Max = 65535, Value = 0, Tooltip = "0 = auto-bind. Set if device requires fixed source port." },
    { Name = "PollIntervalMs", Type = "integer", Min = 200, Max = 5000, Value = 1000 },
    { Name = "ReconnectBackoffMs", Type = "integer", Min = 1000, Max = 10000, Value = 3000 }
  }
end

-- Control definitions
local function addControl(ctrls, name, pretty, controlType, extras)
  local c = { Name = name, ControlType = controlType, PrettyName = pretty, UserPin = true }
  if extras then
    for k, v in pairs(extras) do c[k] = v end
  end
  table.insert(ctrls, c)
end

function GetControls(props)
  local ctrls = {
    { Name = "PluginInfoText", ControlType = "Text", PrettyName = "Status~Plugin Info" },
    { Name = "Online", ControlType = "Indicator", IndicatorType = "Status", PrettyName = "Status~Online", UserPin = true },
    { Name = "LastError", ControlType = "Text", PrettyName = "Status~Last Error" },
    { Name = "AllInputsMute", ControlType = "Button", ButtonType = "Toggle", PrettyName = "Global~All Inputs Mute", UserPin = true },
    { Name = "AllOutputsMute", ControlType = "Button", ButtonType = "Toggle", PrettyName = "Global~All Outputs Mute", UserPin = true }
  }

  for key, def in pairs(channelDefinitions) do
    for i = 1, def.count do
      local baseName = string.format("%s_%d", key, i)
      local label = string.format("%s %d", def.label, i)
      addControl(ctrls, baseName .. "_mute", string.format("%s~%s~Mute", def.type == "input" and "Inputs" or "Outputs", label), "Button", { ButtonType = "Toggle" })
      addControl(ctrls, baseName .. "_vol", string.format("%s~%s~Volume", def.type == "input" and "Inputs" or "Outputs", label), "Knob", { ControlUnit = "dB", Min = -90, Max = 0, DefaultValue = -10 })
    end
  end

  for _, pair in ipairs(stereoPairs) do
    addControl(ctrls, pair.key .. "_mode", string.format("Stereo~%s~Mode", pair.label), "Selector", { Values = pairModes, DefaultValue = "Off", UserPin = true })
    addControl(ctrls, pair.key .. "_mute", string.format("Stereo~%s~Mute", pair.label), "Button", { ButtonType = "Toggle", UserPin = true })
    addControl(ctrls, pair.key .. "_vol", string.format("Stereo~%s~Volume", pair.label), "Knob", { ControlUnit = "dB", Min = -90, Max = 0, DefaultValue = -10, UserPin = true })
  end

  return ctrls
end

-- UI Layout (Audac Touch inspired)
function GetControlLayout(props)
  local layout = {
    { Name = "Header", Type = "Text", Text = "AUDAC NIO240 Control", FontSize = 20, Bold = true },
    { Name = "LogoAudac", Type = "Picture", File = "audac_logo.png", Width = 120, Height = 40 },
    { Name = "LogoNikita", Type = "Picture", File = "nikita_logo.png", Width = 120, Height = 40 },
    { Name = "Status", Type = "Group", Children = { "PluginInfoText", "Online", "LastError" } },
    { Name = "Global", Type = "Group", Children = { "AllInputsMute", "AllOutputsMute" } }
  }

  local function addStrip(def, index)
    local baseName = string.format("%s_%d", def.key, index)
    table.insert(layout, {
      Name = baseName .. "_strip",
      Type = "GroupBox",
      Title = def.label .. " " .. index,
      Style = "Dark",
      Children = { baseName .. "_mute", baseName .. "_vol" }
    })
  end

  for key, def in pairs(channelDefinitions) do
    for i = 1, def.count do
      addStrip({ key = key, label = def.label }, i)
    end
  end

  for _, pair in ipairs(stereoPairs) do
    table.insert(layout, {
      Name = pair.key .. "_strip",
      Type = "GroupBox",
      Title = pair.label .. " Stereo",
      Style = "Dark",
      Children = { pair.key .. "_mode", pair.key .. "_mute", pair.key .. "_vol" }
    })
  end

  return layout
end

-- State management
local function initChannelState()
  for key, def in pairs(channelDefinitions) do
    for i = 1, def.count do
      local id = string.format("%s_%d", key, i)
      channelState[id] = { mute = false, vol = -10 }
    end
  end
  for _, pair in ipairs(stereoPairs) do
    pairModeState[pair.key] = "Off"
  end
end

initChannelState()

-- Command queue to rate limit
local commandQueue = {}
local function enqueueCommand(cmd)
  table.insert(commandQueue, cmd)
end

local function processQueue(transport)
  if #commandQueue == 0 then return end
  local cmd = table.remove(commandQueue, 1)
  transport:send(cmd)
end

-- Control bindings
local transport = Transport:new(function(raw)
  local responses, remainder = parse_response(raw)
  transport.buffer = remainder or ""
  for _, rsp in ipairs(responses) do
    local target = rsp.target or ""
    local command = rsp.command or ""
    local args = trim(rsp.args or "")
    local function updateChannel(base, idx)
      local key = string.format("%s_%d", base, idx)
      local muteKey = key .. "_mute"
      local volKey = key .. "_vol"
      if command == "MUTE" then
        local val = args == "1"
        channelState[key].mute = val
        if Controls[muteKey] then Controls[muteKey].Boolean = val end
      elseif command == "VOLUME" then
        local num = tonumber(args)
        if num then
          channelState[key].vol = num
          if Controls[volKey] then Controls[volKey].Value = num end
        end
      end
    end

    local baseTarget, indexStr = target:match("([^>]+)>(%d+)")
    if baseTarget and indexStr then
      local idx = tonumber(indexStr)
      if baseTarget == "INPUT_LINE" then updateChannel("inputs_line", idx) end
      if baseTarget == "INPUT_DANTE" then updateChannel("inputs_dante", idx) end
      if baseTarget == "INPUT_BLUETOOTH" then updateChannel("inputs_bt", idx) end
      if baseTarget == "OUTPUT_DANTE" then updateChannel("outputs_dante", idx) end
    elseif target == "ALL_IN" or target == "ALL_OUT" then
      local val = args == "1"
      if target == "ALL_IN" then Controls.AllInputsMute.Boolean = val end
      if target == "ALL_OUT" then Controls.AllOutputsMute.Boolean = val end
    end
  end
  return transport.buffer
end, function(status)
  if Controls.Online then
    Controls.Online.Boolean = status == "Connected"
  end
  if status ~= "Connected" and Controls.LastError then
    Controls.LastError.String = status
  end
  if status == "Connected" then
    pollTimer:Start(Properties.PollIntervalMs.Value)
    queueTimer:Start(200)
    reconnectTimer:Stop()
  else
    pollTimer:Stop()
    reconnectTimer:Stop()
    reconnectTimer:Start(Properties.ReconnectBackoffMs.Value)
  end
end)

-- Poll timer
pollTimer.EventHandler = function()
  local addr = Properties.DeviceAddress.Value
  for key, def in pairs(channelDefinitions) do
    for i = 1, def.count do
      local target = string.format("%s>%d>VOLUME>1", def.baseTarget, i)
      enqueueCommand(build_command(addr, target, "VOLUME", "", "GET_REQ"))
      enqueueCommand(build_command(addr, target, "MUTE", "", "GET_REQ"))
    end
  end
end

-- Queue processor timer
queueTimer.EventHandler = function()
  processQueue(transport)
end

-- Stereo helpers
local function handleStereoSync(pairKey, controlType, value)
  local mode = pairModeState[pairKey]
  if mode ~= "Linked" then return end
  for _, pair in ipairs(stereoPairs) do
    if pair.key == pairKey then
      for _, member in ipairs(pair.members) do
        if controlType == "mute" then
          local ctrl = Controls[member .. "_mute"]
          if ctrl then ctrl.Boolean = value end
        elseif controlType == "vol" then
          local ctrl = Controls[member .. "_vol"]
          if ctrl then ctrl.Value = value end
        end
      end
    end
  end
end

-- Control handlers
local function registerHandlers()
  Controls.AllInputsMute.EventHandler = function(ctrl)
    local addr = Properties.DeviceAddress.Value
    local val = ctrl.Boolean and "1" or "0"
    enqueueCommand(build_command(addr, "ALL_IN", "MUTE", val, "SET_REQ"))
  end
  Controls.AllOutputsMute.EventHandler = function(ctrl)
    local addr = Properties.DeviceAddress.Value
    local val = ctrl.Boolean and "1" or "0"
    enqueueCommand(build_command(addr, "ALL_OUT", "MUTE", val, "SET_REQ"))
  end

  for key, def in pairs(channelDefinitions) do
    for i = 1, def.count do
      local base = string.format("%s_%d", key, i)
      local target = string.format("%s>%d>VOLUME>1", def.baseTarget, i)
      local muteCtrl = Controls[base .. "_mute"]
      local volCtrl = Controls[base .. "_vol"]
      if muteCtrl then
        muteCtrl.EventHandler = function(c)
          local addr = Properties.DeviceAddress.Value
          local val = c.Boolean and "1" or "0"
          enqueueCommand(build_command(addr, target, "MUTE", val, "SET_REQ"))
        end
      end
      if volCtrl then
        volCtrl.EventHandler = function(c)
          local addr = Properties.DeviceAddress.Value
          local val = string.format("%.1f", c.Value)
          enqueueCommand(build_command(addr, target, "VOLUME", val, "SET_REQ"))
        end
      end
    end
  end

  for _, pair in ipairs(stereoPairs) do
    local modeCtrl = Controls[pair.key .. "_mode"]
    local muteCtrl = Controls[pair.key .. "_mute"]
    local volCtrl = Controls[pair.key .. "_vol"]
    if modeCtrl then
      modeCtrl.EventHandler = function(c)
        pairModeState[pair.key] = c.String
      end
    end
    if muteCtrl then
      muteCtrl.EventHandler = function(c)
        handleStereoSync(pair.key, "mute", c.Boolean)
        for _, member in ipairs(pair.members) do
          local mCtrl = Controls[member .. "_mute"]
          if mCtrl then mCtrl.EventHandler(mCtrl) end
        end
      end
    end
    if volCtrl then
      volCtrl.EventHandler = function(c)
        handleStereoSync(pair.key, "vol", c.Value)
        for _, member in ipairs(pair.members) do
          local vCtrl = Controls[member .. "_vol"]
          if vCtrl then vCtrl.EventHandler(vCtrl) end
        end
      end
    end
  end
end

-- Connection management
local function startConnection()
  transport:connect(Properties.DeviceIP.Value, Properties.DevicePort.Value, Properties.LocalPort.Value)
  pollTimer:Start(Properties.PollIntervalMs.Value)
  queueTimer:Start(200)
end

reconnectTimer.EventHandler = function()
  startConnection()
end

function OnPropertyChanged(property)
  if property == "DeviceIP" or property == "DevicePort" or property == "LocalPort" then
    transport:close()
    startConnection()
  elseif property == "PollIntervalMs" then
    pollTimer:Stop()
    pollTimer:Start(Properties.PollIntervalMs.Value)
  end
end

-- Initialization
local initialized = false
function OnDriverInit()
  if initialized then return end
  if Controls.PluginInfoText then
    Controls.PluginInfoText.String = string.format("%s v%s", PluginInfo.Name, PluginInfo.Version)
  end
  registerHandlers()
  startConnection()
  initialized = true
end

function OnDriverLateInit()
  -- Additional late initialization if needed
end

-- Graceful shutdown
function OnDriverUnload()
  pollTimer:Stop()
  queueTimer:Stop()
  reconnectTimer:Stop()
  transport:close()
end
